### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by kapo** [konti-kun/redmine_mapping_board#2]
Hello,
I am getting this error, from what I googled, it seems like issue with RAILS 5

[redmine@its-test redmine]$ rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePositions < ActiveRecord::Migration[4.2]
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:528:in `inherited'
/home/redmine/redmine-4.0.1/plugins/redmine_mapping_board/db/migrate/001_create_positions.rb:1:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:986:in `load_migration'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:982:in `migration'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1350:in `use_transaction?'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1342:in `ddl_transaction'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:498:in `up'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:530:in `migrate_plugin'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:471:in `migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:485:in `block in migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:484:in `each'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:484:in `migrate'
/home/redmine/redmine-4.0.1/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/redmine/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was writt                                                                                                                    en for:

  class CreatePositions < ActiveRecord::Migration[4.2]
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:528:in `inherited'
/home/redmine/redmine-4.0.1/plugins/redmine_mapping_board/db/migrate/001_create_positions.rb:1:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:986:in `load_migration'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:982:in `migration'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1350:in `use_transaction?'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1342:in `ddl_transaction'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:498:in `up'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:530:in `migrate_plugin'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:471:in `migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:485:in `block in migrate'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:484:in `each'
/home/redmine/redmine-4.0.1/lib/redmine/plugin.rb:484:in `migrate'
/home/redmine/redmine-4.0.1/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/redmine/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'

[redmine@its-test redmine]$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
[redmine@its-test redmine]$ rails --version
Rails 5.2.2

**Comment by konti-kun** [comment]
Thank you for your issue.
I fixed this issue so please git pull new commits!
