### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by pink-sky** [konti-kun/redmine_mapping_board#4]
> [root@localhost /opt/redmine-test/apps/redmine/htdocs/plugins]$ rake redmine:plugins:migrate
(in /opt/redmine-test/apps/redmine/htdocs)
rake aborted!
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:538:in `get_all_versions'
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:546:in `current_version'
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:528:in `migrate_plugin'
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:471:in `migrate'
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:485:in `block in migrate'
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:484:in `each'
/opt/redmine-test/apps/redmine/htdocs/lib/redmine/plugin.rb:484:in `migrate'
/opt/redmine-test/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

> Environment:
  Redmine version                4.0.2.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.14

**Comment by konti-kun** [comment]
Thank you for trying my plugin.
This error is the DB connection error. Therefore I think that your configuration is not currect.
Have you been succeeded installation of redmine without this plugin?

**Comment by pink-sky** [comment]
now installed redmine version is bitnami packege 4.0.2..



2019년 3월 30일 (토) 오후 7:36, konti-kun <notifications@github.com>님이 작성:

**Comment by konti-kun** [comment]
OK.
Please try rake command at the redmine directory, not a plugin directory.
In my environment, plugins put in “<<redime_path>>/plugins”. I don’t know “htdocs” directory.

**Comment by konti-kun** [comment]
I haven’t known bitnami so I haven’t try your case yet. I will try bitnami.

**Comment by konti-kun** [comment]
Can you try the following command?
    bundle rake redmine:plugins:migrate RAILS_ENV=production

**Comment by miniream** [comment]
[root@localhost /opt/redmine-test/apps/redmine/htdocs/plugins]$ bundle rake redmine:plugins:migrate RAILS_ENV=production
Could not find command "rake".
[root@localhost /opt/redmine-test/apps/redmine/htdocs/plugins]$

**Comment by miniream** [comment]
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
and complete migration
but main page not open(error page)

> bundle exec rake redmine:plugins:migrate RAILS_ENV=production
== 1 CreatePositions: migrating ===============================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:positions, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.2194s
== 1 CreatePositions: migrated (0.2198s) ======================================

== 2 CreateNotes: migrating ===================================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:notes, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.2743s
== 2 CreateNotes: migrated (0.2746s) ==========================================

== 3 DropTablePositions: migrating ============================================
-- drop_table(:positions)
   -> 0.1247s
== 3 DropTablePositions: migrated (0.1248s) ===================================

== 4 CreateMappingboards: migrating ===========================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:mappingboards, {:options=>"ENGINE=InnoDB", :id=>:integer})
   -> 0.2079s
-- add_reference(:notes, :mappingboard, {:type=>:integer, :foreign_key=>true, :index=>false})
   -> 0.9434s
-- remove_reference(:notes, :project, {:foreign_key=>true})
   -> 0.4091s
-- add_index(:notes, [:mappingboard_id, :issue_id], {:unique=>true})
   -> 0.1832s
-- add_index(:notes, [:mappingboard_id, :number], {:unique=>true})
   -> 0.0917s
== 4 CreateMappingboards: migrated (1.8358s) ==================================

[root@localhost /opt/redmine-test/apps/redmine/htdocs]$

Error:
Web application could not be started
Error ID:
c9b68aff
Details:
Web application could not be started by the Phusion Passenger application server.

Please read the Passenger log file (search for the Error ID) to find the details of the error.

You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger is run with environment set to development and/or with the friendly error pages option set to on.

For more information about configuring environment and friendly error pages, see:

Nginx integration mode
Apache integration mode
Standalone mode

**Comment by konti-kun** [comment]
I can't judge your status so I want more error logs.

This plugin don't have any dependencies so it is probably not difficult to install this plugin.
However this plugin uses CDN for D3.js: Javascript library so browser need to access to the internet.

**Comment by goodnewz** [comment]
I have a similar problem. Looking at the passenger logs I see the following error reported: 

App 10612 output: Error: The application encountered the following error: /var/www/redmine/plugins/redmine_mapping_board/app/controllers/concerns/common.rb:11: syntax error, unexpected end-of-input, expecting end (SyntaxError)

**Comment by konti-kun** [comment]
Thank you for reports.

That is my mistake.
"common.rb" had not been used in this plugin so I have just removed code in Common.
Please pull latest codes!

**Comment by goodnewz** [comment]
Thank you. Just did a test. Everything works as expected.
