### ISSUE TITLE
Images in Documentaion

### ISSUE THREAD

**Issue by phuicy** [konti-kun/redmine_mapping_board#5]
Hi,

Thanks for your great work. For others it would be great to include a screenshot in the readme so that we can tell what we are installing.

thanks,
Guy

**Comment by konti-kun** [comment]
Thank you for your advise.
I have wanted to do it but I put off documentation than adding functions or fixing bugs.

This plugin has advantage of GUI so It is important that this plugin has document including images.
I will write that soon!

**Comment by konti-kun** [comment]
I have tried adding the main image to the readme.

**Comment by phuicy** [comment]
Thank you this is excellent! I have another suggestion I am going to open another issue for.
