### ISSUE TITLE
Notes and Group

### ISSUE THREAD

**Issue by phuicy** [konti-kun/redmine_mapping_board#6]
It would be great if we could leave notes or groupings on the background, like drawing on a whiteboard with sticky notes on it. This would make it a very powerful brainstorming and kanban tool.

Thanks, 
Guy

**Comment by konti-kun** [comment]
You can already leave a note.
If you hover the mouse on a note, “X” button appears and you click it then the note is deleted. This action only delete a note not delete issue.

**Comment by konti-kun** [comment]
I have released v0.3.0.
This version add image background in whiteboard and use multi whiteboard.
It may not be what you imagine but you can use these function in brainstorming.
I will develop display relationships of issues next.

**Comment by konti-kun** [comment]
I released function displaying relationships.
